# -*- coding: utf-8 -*-
"""Assignement1_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmfmJ7yiYxadWVcivuspj3w3L4mVZA5h

# **Trailers Analysis by Genre: Audio Focus**

**By : Kenza Charfi**

**Objective:**
Analyze and compare audio features of film trailers from three genres using Python: **Action**, **Horror**, and **Romance**.

# **Setup Environment**
"""

!pip install librosa matplotlib numpy IPython

!pip install yt_dlp moviepy librosa

#Libraries
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import IPython.display as ipd

"""# **Load and Preprocess Audio**"""

import yt_dlp
from moviepy.editor import VideoFileClip
import librosa
import os

def download_youtube_audio(url, base_filename="trailer", duration=120):
    # Force yt_dlp to use webm and set final filename
    output_filename = f"{base_filename}.webm"

    ydl_opts = {
        'format': 'bestvideo+bestaudio',
        'outtmpl': output_filename
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])

    # Use correct filename (.webm instead of .mp4)
    clip = VideoFileClip(output_filename).subclip(0, duration)
    audio_path = output_filename.replace(".webm", ".wav")
    clip.audio.write_audiofile(audio_path, codec='pcm_s16le')

    return audio_path

# Trailer URLs
trailer_urls = {
    "Action": "https://www.youtube.com/watch?v=avz06PDqDbM",
    "Horror": "https://www.youtube.com/watch?v=k10ETZ41q5o",
    "Romance": "https://www.youtube.com/watch?v=BjJcYdEOI0k"
}

# Process all trailers
audio_data = {}
sr = 22050

for genre, url in trailer_urls.items():
    print(f"Downloading {genre} trailer...")
    audio_path = download_youtube_audio(url, base_filename=f"{genre.lower()}_trailer", duration=120)
    y, _ = librosa.load(audio_path, sr=sr)
    audio_data[genre] = y

"""# **Extract features:**"""

def analyze_audio(y, sr):
    features = {}
    tempo, _ = librosa.beat.beat_track(y=y, sr=sr)
    features["Tempo"] = float(tempo)
    features["RMS"] = np.mean(librosa.feature.rms(y=y))
    features["Spectral Centroid"] = np.mean(librosa.feature.spectral_centroid(y=y, sr=sr))
    features["Chroma"] = np.mean(librosa.feature.chroma_stft(y=y, sr=sr))
    return features

results = {}
for genre, y in audio_data.items():
    results[genre] = analyze_audio(y, sr)

import pandas as pd
df = pd.DataFrame(results).T.round(2)
df

"""# **Visualization**
Tempo and Loudness by Genre
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 4))
plt.bar(df.index, df["Tempo"])
plt.title("Tempo (BPM) by Genre")
plt.ylabel("Beats per Minute")
plt.show()

plt.figure(figsize=(10, 4))
plt.bar(df.index, df["RMS"])
plt.title("Average Loudness (RMS Energy) by Genre")
plt.ylabel("RMS Energy")
plt.show()